[server]
headless = true
address = "0.0.0.0"
port = 8502
maxUploadSize = 200
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
